# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2caa76cb5dd17f4794e18ac72231223f94bae514c467e58205b4d78d5a74faf737cdb70d265a779a09fd852a2ff1ef940a0f0492318c1c7316599ec4435cc352

test:
  secret_key_base: 284438601120a7c081ac8821c15a3cb098e5e995823936f3cc61738bacc96704a811c24ca9d5f53e60924018451d7b0dc2ea5f1d9dccf020cd73bf87ebb0e9ce

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
